Fix maj 23/08
Traceback (most recent call last):
  File "determine_maj.py", line 95, in <module>
    check_and_execute_script(url, file_path, script_to_execute)
TypeError: check_and_execute_script() missing 1 required positional argument: 'path_script_sms'